# Outros Tópicos {#others1}

**Aviso:** este capítulo está em construção. O que segue abaixo é apenas um rascunho.


## Projetos, Github, e Addins

Existem muitas ferramentas que facilitam a vida do programador. Aqui ensinarei sobre como organizar seus, bem, projetos, com os "Projetos" do RStudio. Darei uma introdução ao controle de versão com Git e sua integração com o RStudio, uma ferramenta que mais programadores deveriam utilizar. E por fim, algumas extensões de "qualidade de vida" disponíveis para o RStudio.



## Debbuging

Um dos maiores benefícios da abordagem da primeira parte do livro é entender melhor as causas dos erros. Aqui, mostrarei como esse conhecimento pode ser aplicado, utilizando as ferramentas de debugging do RStudio.



## Gerenciamento de Memória e Performance

Um tema mais avançado, para aqueles que precisam fazer códigos eficientes, é como o R gerencia a memória. Darei dicas objetivas para otimizar seu código.



## Organização de Código e Boas Práticas

Escrever códigos de maneira limpa e estética é importante, para evitar erros e deixá-los entendíveis. Falarei sobre estilos de código, principalmente o estilo tidyverse, bem como alguns pacotes que ajudam o programador, _lintr_, e _styler_.



<div class="double-hrule"></div>

## Complemento {.unlisted .unnumbered}

### Recapitulando {-}


---

### Exercícios {-}


---

### Dicionário de Funções {-}


---

### Referências {-}

