# Parte III - Ciência de Dados: Processar e Visualizar {#intro3 .unnumbered}

:::{.warn}
este capítulo está em construção. O que segue abaixo é apenas um rascunho.
:::

Bem vindo à segunda parte deste livro. Aqui, foco em ensinar sobre o que é ciência de dados, e o formato de _tidy data_. Ensino também o processo de obter esse formato: importar, arrumar, manipular, e unir bases de dados. Por fim, vamos descobrir como habilidades de visualização de dados para explorá-los, obtendo intuições para a etapa da modelagem.

Os capítulos estão organizados por etapas de um projeto de ciência de dados:

- Capítulo \@ref(ds): descrevo os fundamentos e etapas de um projeto de ciência de dados e o que é _tidy data_.
- Capítulo \@ref(import-tidy): descrevo como importar e arrumar dados.
- Capítulo \@ref(manipulate): descrevo outras manipulações que dados já arrumados podem exigir.
- Capítulo \@ref(unite): descrevo unir (_merge_) várias bases de dados em uma só.
- Capítulo \@ref(visualizate): descrevo os fundamentos da visualização de dados, e como explorar dados para adquirir intuições.
- Recapitulado: seção para retomar os conteúdos aprendidos.
