# Parte IV - Ciência de Dados: Modelagem {#intro4 .unnumbered}

:::{.warn}
este capítulo está em construção. O que segue abaixo é apenas um rascunho.
:::

Bem vindo à quarta e última parte deste livro. Aqui, irei ensinar mais uma etapa de projetos de ciência de dados, a modelagem.

Agora sim, o estilo do livro é bem mais mostrar as capacidades do R através de exemplos, do que o estudo teórico das outras seções.

Os temas são:

- Capítulo \@ref(stats-prob): apresento como resolver problemas comuns em probabilidade e estatística, o assunto central do R.
- Capítulo \@ref(regression): apresento como realizar análises de regressões, com base nos vários modelos comuns inclusos no R.
- Capítulo \@ref(ml): complementar à regressões, apresento rapidamente alguns _frameworks_ para modelos mais complexos de _machine learning_.
- Capítulo \@ref(others4): para servir de referência, listo outras aplicações de possível interesse, especialmente aquelas com relação aos conceitos deste livro.
- Recapitulando: seção para retomar os conteúdos aprendidos.
